//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourPal1._0.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activity()
        {
            this.Clients = new HashSet<Client>();
        }
    
        public int Id { get; set; }
        [Required]
        [Display(Name = "Destination")]
        public string Destination { get; set; }
        [Required]
        [Display(Name = "TimeToGo")]
        public string TimeToGo { get; set; }

        public string BriefDescription { get; set; }
        [Required]
        [Display(Name = "Administrator")]
        public int AdministratorId { get; set; }
        [Required]
        [Display(Name = "Capacity")]
        public string MaximumNumberOfParticipant { get; set; }
    
        public virtual Administrator Administrator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Clients { get; set; }
    }
}
