//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourPal1._0.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<preferredPartner> preferredPartners { get; set; }

        public System.Data.Entity.DbSet<TourPal1._0.Models.Image> Images { get; set; }
    }
}
