//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourPal1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class preferredPartner
    {
        public int Id { get; set; }
        public string PartnerId { get; set; }
        public int ClientId { get; set; }
        public System.DateTime ThumbedDate { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
